add -v option to build for vm without avx, avx2 etc...

diff --git a/bamboo/build-tf b/bamboo/build-tf
--- a/bamboo/build-tf
+++ b/bamboo/build-tf
@@ -1,5 +1,29 @@
 #! /bin/bash -e
 
+VM_BUILD=0
+while getopts "v" opt; do
+case $opt in
+        v)
+                VM_BUILD=1
+        ;;
+        \?)
+                echo "Invalid option: -$OPTARG" >&2
+                exit 1
+         ;;
+        :)
+                echo "Invalid Input" >&2
+                exit 1
+        ;;
+        esac
+done
+shift $(($OPTIND - 1))
+
+CPU_FLAGS="--copt=-mavx --copt=-mavx2 --copt=-mfma"
+if [ "$VM_BUILD" = "1" ]; then
+        echo "Building without cpu optimisation"
+        CPU_FLAGS=""
+fi
+
 cd "$(dirname $0)/.."
 #fix makefile for debug
 sed -i "s/name = \"libtensorflow\.so\",/name = \"libtensorflow\.so\",\n    linkopts = \[\"-Wl,--version-script=tensorflow\/tf_version_script\.lds\"\],/g" tensorflow/BUILD
@@ -8,9 +32,9 @@ rm -rf /tmp/tensorflow_pkg
 #all default options
 yes "" | ./configure
 #python build (and headers that will be installed in /usr/local/lib/python2.7/dist-packages/tensorflow/include/)
-bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --copt=-mavx --copt=-mavx2 --copt=-mfma --local_resources 2048,4,1.0
+bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package ${CPU_FLAGS} --local_resources 2048,4,1.0
 ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
 sudo pip install /tmp/tensorflow_pkg/tensorflow*
 #build lib
-bazel build //tensorflow:libtensorflow.so -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --local_resources 2048,4,1.0
+bazel build //tensorflow:libtensorflow.so -c opt ${CPU_FLAGS} --local_resources 2048,4,1.0
 
